version: '3'
services:
  pypicloud:
    command: sh -c '/wait-for -t 30 mysql:3306 -- uwsgi --die-on-term /etc/pypicloud/config.ini'
    depends_on:
      - mysql
    image: stevearc/pypicloud
    ports:
      - "8080:8080"
    volumes:
      - ./config-mysql.ini:/etc/pypicloud/config.ini:ro
      - ./wait-for:/wait-for:ro
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: pypi
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
